import type { ComponentProps } from 'solid-js'

export type IconProps = ComponentProps<'svg'>

export { AtomIcon } from './AtomIcon'
export { BilibiliIcon } from './BilibiliIcon'
export { BriefcaseIcon } from './BriefcaseIcon'
export { CalendarIcon } from './CalendarIcon'
export { CheckDoubleTickIcon } from './CheckDoubleTickIcon'
export { ClipboardCheckIcon } from './ClipboardCheckIcon'
export { ClipboardDataIcon } from './ClipboardDataIcon'
export { CloudIcon } from './CloudIcon'
export { CursorClickIcon } from './CursorClickIcon'
export { CursorIcon } from './CursorIcon'
export { DashboardIcon } from './DashboardIcon'
export { ExternalLinkIcon } from './ExternalLinkIcon'
export { EyeCloseIcon } from './EyeCloseIcon'
export { EyeOpenIcon } from './EyeOpenIcon'
export { FilterHorizontalIcon } from './FilterHorizontalIcon'
export { GitHubBrandIcon } from './GitHubBrandIcon'
export { GitHubIcon } from './GitHubIcon'
export { GoogleBrandIcon } from './GoogleBrandIcon'
export { HomeIcon } from './HomeIcon'
export { HourglassIcon } from './HourglassIcon'
export { Layers3Icon } from './Layers3Icon'
export { LightningIcon } from './LightningIcon'
export { MailIcon } from './MailIcon'
export { MinusCircleIcon } from './MinusCircleIcon'
export { MoonIcon } from './MoonIcon'
export { NewCommentIcon } from './NewCommentIcon'
export { PencilSwooshIcon } from './PencilSwooshIcon'
export { ScriptIcon } from './ScriptIcon'
export { SparkleIcon } from './SparkleIcon'
export { SubscriberIcon } from './SubscriberIcon'
export { SunIcon } from './SunIcon'
export { TagIcon } from './TagIcon'
export { TelegramIcon } from './TelegramIcon'
export { TiltedSendIcon } from './TiltedSendIcon'
export { TwitterIcon } from './TwitterIcon'
export { UFOIcon } from './UFOIcon'
export { UserArrowLeftIcon } from './UserArrowLeftIcon'
export { UserSecurityIcon } from './UserSecurityIcon'
export { UsersIcon } from './UsersIcon'
export { UTurnLeftIcon } from './UTurnLeftIcon'
export { XIcon } from './XIcon'
export { XSquareIcon } from './XSquareIcon'
export { YouTubeIcon } from './YouTubeIcon'
